const data={TR:['WhatsApp','Telegram','Instagram','Google','TikTok','Facebook'],US:['WhatsApp','Google','Telegram','Instagram','TikTok','Discord'],GB:['WhatsApp','Telegram','Google','Instagram','Facebook'],DE:['WhatsApp','Telegram','Google','Instagram'],FR:['WhatsApp','Telegram','Instagram','Google'],CA:['WhatsApp','Google','Telegram','Instagram'],IT:['WhatsApp','Telegram','Instagram'],ES:['WhatsApp','Telegram','Google'],AU:['WhatsApp','Google','Telegram']};
const icons={WhatsApp:'💬',Telegram:'✈️',Instagram:'◎',Google:'G',TikTok:'♪',Facebook:'f',Discord:'◉'};
const prices={TR:18,US:25,GB:24,DE:22,FR:23,CA:25,IT:22,ES:21,AU:27};
const country=document.querySelector('#country'),service=document.querySelector('#service'),cards=document.querySelector('#cards'),stock=document.querySelector('#stock'),price=document.querySelector('#price'),modal=document.querySelector('#modal');
country.onchange=()=>{service.innerHTML='<option value="">Servis seçin</option>';cards.innerHTML='';(data[country.value]||[]).forEach((name,i)=>{service.add(new Option(name,name));const d=document.createElement('div');d.className='card';d.innerHTML=`<b>${icons[name]||'●'}</b><h3>${name}</h3><p>Canlı stok ve sipariş takibi</p><button data-i="${i}">Seç</button>`;cards.appendChild(d)});stock.textContent='Hazır';price.textContent='Servis seçin'};
service.onchange=()=>{if(!service.value){stock.textContent='—';price.textContent='Fiyat bekleniyor';return}const i=data[country.value].indexOf(service.value);stock.textContent=Math.floor(20+Math.random()*80);price.textContent='₺'+(prices[country.value]+i*2)+',00 / işlem'};
cards.onclick=e=>{if(e.target.tagName!=='BUTTON')return;service.value=data[country.value][+e.target.dataset.i];service.dispatchEvent(new Event('change'));open()};
function open(){document.querySelector('#summary').innerHTML=`<div><span>Ülke</span>${country.options[country.selectedIndex].text}</div><div><span>Servis</span>${service.value}</div><div><span>Stok</span>${stock.textContent}</div><div><span>Fiyat</span>${price.textContent}</div>`;modal.classList.remove('hidden')}
document.querySelector('#x').onclick=()=>modal.classList.add('hidden');
document.querySelector('#confirm').onclick=()=>{const id='VNX-'+Math.random().toString(36).slice(2,8).toUpperCase();const body=document.querySelector('#ordersBody');if(body.rows.length===1&&body.rows[0].cells.length===1)body.innerHTML='';body.insertAdjacentHTML('afterbegin',`<tr><td>${id}</td><td>${service.value}</td><td>Bekleniyor…</td><td style="color:#4be28b">● İşleniyor</td></tr>`);modal.classList.add('hidden');location.hash='orders'};
